import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Career Compass AI",
  description: "Generated by create next app",
};

// Layout component for the entire app
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} `}
      >
        {/* Dark theme */}
        <ClerkProvider appearance={{ baseTheme: dark }}>

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />
            <main className="min-h-screen">
              {/* contents of app/page.jsx */}
              {children}
            </main > 
            {/* footer */}

            {/* Toaster notification */}
            <Toaster richColors/>
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-grey-200">
                <p>Copyright by Shyam 2025</p>
              </div>
            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>

    </html>
  );
}
